# -*- coding: utf-8 -*-
"""rank-access_num.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gyKktsAkY5m_5af7Z28KF8ED5vwmDKm3
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import argparse
import os
import sys


def main(read_file_name):
  index = read_file_name.rfind(".")
  output_img_name = read_file_name[:index]
  df = pd.read_csv(read_file_name,
                 skipinitialspace=True, delim_whitespace=True, lineterminator="\n", 
                 comment='=' ## Convert address to page(4KB)
                 )

  plt.style.use('default')
  plt.rcParams['figure.figsize'] = (12, 10)
  #plt.rcParams['font.size'] = 12

  fig, ax = plt.subplots(figsize=(12,10))
  x = df['rank']
  y = df['access_number']

  plt.scatter(x, y, color='blue', s=1)

  ax.set_xlabel('LRU rank')
  ax.set_ylabel('access count')
  ax.set_xscale('log')
  ax.set_yscale('log')
  ax.legend(loc='best')

  plt.savefig(f'{output_img_name}.png')

def is_valid_file(parser, arg):
  if not os.path.exists(arg):
      parser.error("The file %s does not exist" % arg)
  else:
      return arg


if __name__ == "__main__":
  parser = argparse.ArgumentParser(description = 'draw x-ranking(LRU) y-accessCount graph log scale')
  parser.add_argument("-i", dest="filename", required=True,
                    help="input ranking-accessCount data",
                    type=lambda x: is_valid_file(parser, x))
  args = parser.parse_args()
  main(args.filename)

